name: Linux Build 
#(Docker Jammy, Qt 6.9.3, AppImage)

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - name: Install base deps
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential \
            cmake \
            git
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Qt 6 (version in Ubuntu 24.04)
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y qt6-base-dev

      # - name: Install Qt 6 (6.9.3)
      #   uses: jurplel/install-qt-action@v4
      #   with:
      #     version: '6.9.3'
      #     target: 'desktop'
      #     cache: true
      #     setup-python: false # use container python

      - name: Configure (CMake + Make)
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$QT_ROOT_DIR/lib/cmake"

      - name: Build
        run: cmake --build build --config Release -j

      # - name: Package AppImage (linuxdeployqt)
      #   run: |
      #     bash ./dist_linux_docker.sh

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: DKV2-AppImage
      #     path: build-dist-linux/DKV2-*.AppImage
